<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'QFGW' => 1,
        'QZFB' => 2,
        'QWZFW' => 3,
        'QWZZB' => 4,
        'QWXCB' => 5,
        'QWMB' => 6,
        'QWWXB' => 7,        
        'QWB' => 8,
        'QSCJGJ' => 9,
        'QSWJ' => 10,
        'QZJW' => 11,
        'QGXJ' => 12,
        'QKJJ' => 13,
        'QWJW' => 14,
        'QRSJ' => 15,
        'QCZJ' => 16,
        'QTJJ' => 17,
        'QSJJ' => 18,
        'QJYJ' => 19,
        'QSHANGWJ' => 20,
        'QMZJ' => 21,
        'QSTHJJ' => 22,
        'QNYNCW' => 23,
        'GAWQFJ' => 24,
        'QSFJ' => 25,
        'QFY' => 26,
        'QJCY' => 27,
        'QWLJ' => 28,
        'QJRJ' => 29,
        'QGZW' => 30,
        'GHHZRZYJWQFJ' => 31,
        'QCGW' => 32,
        'QSHUIWJ' => 33,
        'QYJJ' => 34,
        'QYBJ' => 35,
        'QZWFWB' => 36,
        'QHJB' => 37,
        'QGSL' => 37,
        'TQW' => 39,
        'YGJ' => 40,
        'XGTJ' => 41,
        'DPWJ' => 42,
        'HZJ' => 43,
        'XZZJ' => 44,
        'BGTJ' => 45,
        'CZLJ' => 46,
        'CGGZ' => 47,
        'CZZ' => 48,
        'CGZ' => 49,
        'CHKZ' => 50,
        'DHBZ' => 51,
        'DJCZ' => 52,
        'DLZ' => 53,
        'DMZZ' => 54,
        'DWGZZ' => 55,
        'DMJZ' => 56,
        'DZZZ' => 57,
        'GCZ' => 58,
        'HBTZ' => 59,
        'HXWZ' => 60,
        'HHDZ' => 61,
        'MCZ' => 62,
        'NCCZ' => 63,
        'SMTZ' => 64,
        'SGZZ' => 65,
        'SCDZ' => 66,
        'WQTZ' => 67,
        'XWQZ' => 68,
    );
}
